version: 2
updates:
- package-ecosystem: gradle
  directory: "/app"
  schedule:
    interval: daily
    time: '11:00'
    timezone: Asia/Kolkata
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: io.sentry:sentry-android
    versions:
    - "> 1.7.30"
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: '11:00'
    timezone: Asia/Kolkata
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: io.sentry:sentry-android
    versions:
    - "> 1.7.30"
