language: android
dist: trusty

jdk:
  - openjdk8

android:
  components:
    - tools
    - build-tools-29.0.3
    - extra-android-m2repository
    - android-29
  licenses:
    - ".+"

before_install:
  - yes | sdkmanager 'ndk;21.2.6472646'

script:
  - ./gradlew assembleDebug

notifications:
  email: false

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
